version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres-db
    ports:
      - 5432:5432
    # environment:
    # POSTGRES_USER: postgres
    # POSTGRES_PASSWORD: postgres
    # POSTGRES_DB: workwave-db
    # POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   container_name: prisma-studio
  #   restart: always
  #   ports:
  #     - 4466:4466
  #   environment:
  #     PRISMA_CONFIG: |
  #       managementApiSecret: dirtylittlesecret
  #       port: 5555
  #       databases:
  #         default:
  #           connector: postgres
  #           host: postgres
  #           port: 5432
  #           user: postgres
  #           password: postgres
  #           migrations: true
  #           rawAccess: true
  #           database: postgres-db
  #   depends_on:
  #     - postgres

  # prisma-studio:
  #   image: timothyjmiller/prisma-studio:latest
  #   container_name: prisma-studio
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - 5555:5555

  workwave-dev:
    image: workwaveapp/workwave-dev
    container_name: workwave-application
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npm run dev"

volumes:
  postgres-data:
