version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workwave-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  workwave-dev:
    image: workwaveapp/workwave-dev
    container_name: workwave-application
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  postgres-data:
